In [1]:
#Linear algebra library
#"IntelMKL" and "OpenBLAS"

In [2]:
import numpy as np
A= np.ones((2, 2))

In [3]:
B= np.eye(2, 2)


In [4]:
C= np.zeros((2, 2))

In [5]:
D= np.diag((-3, -4))

In [6]:
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [7]:
a = np.zeros(4, dtype=[('a', 'i4'), ('b', 'f4,u2'), ('c', 'f4', 2)])
a

array([(0, (0., 0), [0., 0.]), (0, (0., 0), [0., 0.]),
       (0, (0., 0), [0., 0.]), (0, (0., 0), [0., 0.])],
      dtype=[('a', '<i4'), ('b', [('f0', '<f4'), ('f1', '<u2')]), ('c', '<f4', (2,))])

In [8]:
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


In [9]:
A = np.array([[1, 1], [2, 1], [3, -3]])

In [10]:
A

array([[ 1,  1],
       [ 2,  1],
       [ 3, -3]])

In [11]:
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


In [12]:
F= np.array([[1, 2, 3, 4, 5], [1, 3, 4, 5, 6]])
F

array([[1, 2, 3, 4, 5],
       [1, 3, 4, 5, 6]])

In [13]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [14]:
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [15]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [16]:
b1=np.array([[2,3,4,4,5,4], [2,3,4,5,3,4]])
b1

array([[2, 3, 4, 4, 5, 4],
       [2, 3, 4, 5, 3, 4]])

In [17]:
type(a2)

numpy.ndarray

In [18]:
type(b1)

numpy.ndarray

In [19]:
len(a2)

1

In [20]:
len(b1)

2

In [21]:
len(a)

6

In [22]:
f=np.zeros(4)
f

array([0., 0., 0., 0.])

In [23]:
g=np.ones(3)
g

array([1., 1., 1.])

In [24]:
h=np.empty(3)
h

array([1., 1., 1.])

In [25]:
i=np.arange(2,15,1)
i

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
j=np.linspace(0,10,num=4, dtype=np.float64)
j

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [27]:
k=np.linspace(0,10,num=4, dtype=np.int32)
k

array([ 0,  3,  6, 10])

In [28]:
L=np.array([[2,3,4,4], [2,3,4,5], [5, 8,7,9]])
L

array([[2, 3, 4, 4],
       [2, 3, 4, 5],
       [5, 8, 7, 9]])

In [29]:
len(L)

3

In [30]:
r= np.arange(11, dtype= np.float64)
r

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
type(r)

numpy.ndarray

In [32]:
r.mean()

5.0

In [33]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [40]:
x = np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
y=3


In [39]:
x*y

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [51]:
np.linspace(0,15,num=2)

array([ 0., 15.])

In [53]:
z= np.array([2, 14, 12, 2.0, 5, 7, 20])
z

array([ 2., 14., 12.,  2.,  5.,  7., 20.])

In [55]:
z.sort()
z

array([ 2.,  2.,  5.,  7., 12., 14., 20.])

### 2-D Array

In [59]:
j= np.array([[1,2,5,4], [8,9,4,5]])
k= np.array([[1,5,5,5], [8,2,4,1]])
print(j)
print(k)

[[1 2 5 4]
 [8 9 4 5]]
[[1 5 5 5]
 [8 2 4 1]]


In [63]:
m= np.concatenate((j,k), axis=1)

In [62]:
j.size

8

In [64]:
m.size

16

In [65]:
o=np.arange(6)

In [67]:
p=o.reshape(3,2)
p

array([[0, 1],
       [2, 3],
       [4, 5]])